apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      name: web-api
      labels:
        env: prod
        app: web-api
        app.kubernetes.io/name: web-api
    spec:
      containers:
      - name: web-api
        image: hiastdevops/webapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http-web-api
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80


---

apiVersion: v1
kind: Service
metadata:
  name: my-ip-service
spec:
  selector:
    app.kubernetes.io/name: web-api
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 80
  type: LoadBalancer